# Generated by Django 5.0.1 on 2024-02-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.PositiveIntegerField(max_length=7),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.BigIntegerField(max_length=10),
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
